edit.command = "nvim"
[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

[git]
    autoCommit = true
    autoPush = false
[data]
	alacritty_size = 12
